### ISSUE TITLE
tailwind.config.js is not working.

### ISSUE THREAD

**Issue by ushironoko** [ushironoko/blog#6]
tailwind.config.jsを置いても無視されてしまう。
moduleの持つデフォルトの設定は使われていてパージ対象からpagesなどは除外されているので普通に動作しているっぽい？
darkmode指定などができなくて不便なので動いてほしい。

**Comment by ushironoko** [comment]
src配下に置く必要ある

**Comment by miyaoka** [comment]
そうなんだ

**Comment by yamanoku** [comment]
学びがありました

**Comment by miyaoka** [comment]
感想欄

**Comment by ushironoko** [comment]
オープンチャットになってて草
